https://github.com/spilabkorea/Domain-LOA/tree/c7a0d6436aa9fbb9cf741eeb8af820bf751de481

In [1]:
import numpy as np
import pandas as pd

In [2]:
from loglizer import loglizer
from loglizer.loglizer import dataloader
from loglizer.loglizer import preprocessing

In [3]:
batch_size = 32
hidden_size = 32
num_directions = 2
topk = 5
train_ratio = 0.2
window_size = 10
epoches = 2
num_workers = 2
device = 0 

In [4]:
(x_train, y_train), (x_test, y_test) = dataloader.load_HDFS(
    'loglizer/data/HDFS/HDFS_100k.log_structured.csv', 
    label_file='loglizer/data/HDFS/anomaly_label.csv',
    window='session', 
    train_ratio=0.5,
    split_type='uniform'
)

====== Input data summary ======
Loading loglizer/data/HDFS/HDFS_100k.log_structured.csv
156 157
Total: 7940 instances, 313 anomaly, 7627 normal
Train: 3969 instances, 156 anomaly, 3813 normal
Test: 3971 instances, 157 anomaly, 3814 normal



In [5]:
x_train[0]

['Receiving block <*> src: /<*> dest: /<*>',
 'BLOCK* NameSystem.allocateBlock:<*>',
 'Receiving block <*> src: /<*> dest: /<*>',
 'Receiving block <*> src: /<*> dest: /<*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'Verification succeeded for <*>',
 'Verification succeeded for <*>',
 'Verification succeeded for <*>']

In [6]:
y_train

array([0, 0, 1, ..., 0, 0, 0])

In [7]:
x_test

array([list(['BLOCK* NameSystem.allocateBlock:<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>']),
       list(['BLOCK* NameSystem.allocateBlock:<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'BLOCK* NameSys

In [8]:
y_test

array([1, 1, 1, ..., 0, 0, 0])

In [9]:
feature_extractor = preprocessing.FeatureExtractor()
x_train = feature_extractor.fit_transform(x_train, term_weighting='tf-idf', normalization='zero-mean')
x_test = feature_extractor.transform(x_test)

====== Transformed train data summary ======
Train data shape: 3969-by-14

====== Transformed test data summary ======
Test data shape: 3971-by-14



In [10]:
mx = 0
mn = 0
count = 0
for x_ in x_train:
    if max(x_) > 1:
        count += 1
    if max(x_) > mx:
        mx = max(x_)
    if min(x_) < mn:
        mn = min(x_)
    
mn, mx, count

(-0.7370563024535449, 1458.3573473362158, 521)

In [11]:
# vectorizer = preprocessing.Vectorizer()
# vectorizer.fit_transform(x_train)

In [12]:
print(x_train[0])
print(type(x_train))
x_train.shape

[-4.88799673e-14  1.03801473e-25  5.87142581e-04  6.01474310e-04
  5.76412880e-04  2.85048410e+00 -1.46142318e-02 -8.35098961e-03
 -8.35098961e-03 -8.35098961e-03 -7.37056302e-01 -3.61975015e-02
 -2.08774740e-03 -2.08774740e-03]
<class 'numpy.ndarray'>


(3969, 14)

In [13]:
max(x_train[0])

2.8504841006486688

In [14]:
print(len(x_test[0]))
x_test[0]

14


array([-4.88799673e-14,  1.03801473e-25,  5.87142581e-04,  6.01474310e-04,
        5.76412880e-04, -5.75102717e-01, -1.46142318e-02, -8.35098961e-03,
       -8.35098961e-03, -8.35098961e-03, -7.37056302e-01, -3.61975015e-02,
       -2.08774740e-03, -2.08774740e-03])

In [15]:
from nn_autoencoder import nn_autoencoder

train_dataset = {
    'x': x_train,
    'y': y_train
}

test_dataset = {
    'x': x_test,
    'y': y_test
}

# model = nn_autoencoder(train_dataset, test_dataset, 0.96)
# model

In [16]:
# true, pred = model

In [17]:
# count = 0
# total = 0

# for t,p in zip(true, pred):
#     if t and p:
#         count += 1
#     total += 1

# count / total

In [18]:
from lstm_autoencoder import lstm_autoencoder

# model_lstm = lstm_autoencoder(train_dataset, test_dataset, 0.96)
# model_lstm

In [19]:
# true, pred, X_pred_train = model_lstm


In [20]:
# count = 0
# total = 0

# for t,p in zip(true, pred):
#     if t and p:
#         count += 1
#     total += 1

# count / total

In [21]:
# X_pred_train

In [22]:
from nn_autoencoder import nn_autoencoder

nn_aenc = nn_autoencoder(train_dataset, test_dataset, 0.96)
nn_aenc

Epoch 1/100
32/32 [==============================] - 2s 31ms/step - loss: 77.6976 - accuracy: 0.0000e+00 - f1_score: -0.1885 - val_loss: 0.6104 - val_accuracy: 0.0053 - val_f1_score: 0.1506
Epoch 2/100
32/32 [==============================] - 1s 22ms/step - loss: 77.4689 - accuracy: 0.0000e+00 - f1_score: -0.1911 - val_loss: 0.5857 - val_accuracy: 0.0053 - val_f1_score: 0.1507
Epoch 3/100
32/32 [==============================] - 1s 23ms/step - loss: 77.3397 - accuracy: 0.0000e+00 - f1_score: -0.1907 - val_loss: 0.5700 - val_accuracy: 0.0000e+00 - val_f1_score: 0.1507
Epoch 4/100
32/32 [==============================] - 1s 22ms/step - loss: 77.2536 - accuracy: 0.0000e+00 - f1_score: -0.1965 - val_loss: 0.5763 - val_accuracy: 0.0000e+00 - val_f1_score: 0.1507
Epoch 5/100
32/32 [==============================] - 1s 22ms/step - loss: 77.1734 - accuracy: 0.0191 - f1_score: -0.1911 - val_loss: 0.6519 - val_accuracy: 0.0000e+00 - val_f1_score: 0.1507
Epoch 6/100
32/32 [=======================

In [23]:
pred = nn_aenc.predict(train_dataset['x'])
pred

array([[-0.00398341, -0.00045702, -0.00760541, ...,  0.01504349,
        -0.00157835, -0.00620154],
       [ 0.02728135,  0.00517251,  0.0342527 , ..., -0.03862829,
         0.02724765,  0.03822621],
       [ 0.0247646 ,  0.00514488,  0.03127128, ..., -0.04091055,
         0.02425061,  0.03459587],
       ...,
       [ 0.02728135,  0.00517251,  0.0342527 , ..., -0.03862829,
         0.02724765,  0.03822621],
       [ 0.0519647 , -0.00162885,  0.06713676, ..., -0.00165693,
         0.05845539,  0.07900315],
       [ 0.02728136,  0.0051725 ,  0.03425267, ..., -0.03862829,
         0.02724772,  0.03822624]], dtype=float32)