https://github.com/spilabkorea/Domain-LOA/tree/c7a0d6436aa9fbb9cf741eeb8af820bf751de481

In [1]:
import numpy as np
import pandas as pd

In [2]:
from loglizer import loglizer
from loglizer.loglizer import dataloader
from loglizer.loglizer import preprocessing

In [3]:
batch_size = 32
hidden_size = 32
num_directions = 2
topk = 5
train_ratio = 0.2
window_size = 10
epoches = 2
num_workers = 2
device = 0 

In [4]:
(x_train, y_train), (x_test, y_test) = dataloader.load_HDFS(
    'loglizer/data/HDFS/HDFS_100k.log_structured.csv', 
    label_file='loglizer/data/HDFS/anomaly_label.csv',
    window='session', 
    train_ratio=0.5,
    split_type='uniform'
)

====== Input data summary ======
Loading loglizer/data/HDFS/HDFS_100k.log_structured.csv
156 157
Total: 7940 instances, 313 anomaly, 7627 normal
Train: 3969 instances, 156 anomaly, 3813 normal
Test: 3971 instances, 157 anomaly, 3814 normal



In [5]:
x_train[0]

['BLOCK* NameSystem.allocateBlock:<*>',
 'Receiving block <*> src: /<*> dest: /<*>',
 'Receiving block <*> src: /<*> dest: /<*>',
 'Receiving block <*> src: /<*> dest: /<*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'PacketResponder <*> for block <*> terminating',
 'Received block <*> of size <*> from /<*>',
 'Verification succeeded for <*>']

In [6]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
x_test

array([list(['BLOCK* NameSystem.allocateBlock:<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'PacketResponder <*> for block <*> terminating', 'Received block <*> of size <*> from /<*>']),
       list(['BLOCK* NameSystem.allocateBlock:<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'Receiving block <*> src: /<*> dest: /<*>', 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>', 'BLOCK* NameSys

In [8]:
y_test

array([1, 1, 1, ..., 0, 0, 0])

In [9]:
feature_extractor = preprocessing.FeatureExtractor()
x_train = feature_extractor.fit_transform(x_train, term_weighting='tf-idf', normalization='zero-mean')
x_test = feature_extractor.transform(x_test)

====== Transformed train data summary ======
Train data shape: 3969-by-14

====== Transformed test data summary ======
Test data shape: 3971-by-14



In [10]:
mx = 0
mn = 0
count = 0
for x_ in x_train:
    if max(x_) > 3:
        count += 1
    if max(x_) > mx:
        mx = max(x_)
    if min(x_) < mn:
        mn = min(x_)
    
mn, mx, count

(-0.7370563024535449, 1458.3573473362158, 31)

In [11]:
# vectorizer = preprocessing.Vectorizer()
# vectorizer.fit_transform(x_train)

In [12]:
print(x_train[0])
print(type(x_train))
x_train.shape

[ 1.03801473e-25 -4.88799673e-14  5.76412880e-04  5.87142581e-04
  6.01474310e-04  5.66759556e-01 -3.61975015e-02 -1.46142318e-02
 -8.35098961e-03 -8.35098961e-03 -8.35098961e-03 -7.37056302e-01
 -2.08774740e-03 -2.08774740e-03]
<class 'numpy.ndarray'>


(3969, 14)

In [13]:
max(x_train[0])

0.5667595557406007

In [14]:
print(len(x_test[0]))
x_test[0]

14


array([ 1.03801473e-25, -4.88799673e-14,  5.76412880e-04,  5.87142581e-04,
        6.01474310e-04, -5.75102717e-01, -3.61975015e-02, -1.46142318e-02,
       -8.35098961e-03, -8.35098961e-03, -8.35098961e-03, -7.37056302e-01,
       -2.08774740e-03, -2.08774740e-03])

In [15]:
from nn_autoencoder import nn_autoencoder

train_dataset = {
    'x': x_train,
    'y': y_train
}

test_dataset = {
    'x': x_test,
    'y': y_test
}

# model = nn_autoencoder(train_dataset, test_dataset, 0.96)
# model

In [16]:
# true, pred = model

In [17]:
# count = 0
# total = 0

# for t,p in zip(true, pred):
#     if t and p:
#         count += 1
#     total += 1

# count / total

In [18]:
from lstm_autoencoder import lstm_autoencoder

# model_lstm = lstm_autoencoder(train_dataset, test_dataset, 0.96)
# model_lstm

In [19]:
# true, pred, X_pred_train = model_lstm


In [20]:
# count = 0
# total = 0

# for t,p in zip(true, pred):
#     if t and p:
#         count += 1
#     total += 1

# count / total

In [21]:
# X_pred_train

In [22]:
from nn_autoencoder import nn_autoencoder

# nn_aenc = nn_autoencoder(train_dataset, test_dataset, 0.96)
# nn_aenc

In [23]:
# pred = nn_aenc.predict(train_dataset['x'])
# pred[0]

In [24]:
train_dataset['x'][0]

array([ 1.03801473e-25, -4.88799673e-14,  5.76412880e-04,  5.87142581e-04,
        6.01474310e-04,  5.66759556e-01, -3.61975015e-02, -1.46142318e-02,
       -8.35098961e-03, -8.35098961e-03, -8.35098961e-03, -7.37056302e-01,
       -2.08774740e-03, -2.08774740e-03])

In [25]:
from lstm_autoencoder import lstm_autoencoder

autoencoder = lstm_autoencoder(train_dataset, test_dataset, 0.96)
autoencoder

Epoch 1/200
32/32 [==============================] - 5s 60ms/step - loss: 77.0003 - accuracy: 0.0068
Epoch 2/200
32/32 [==============================] - 2s 54ms/step - loss: 76.6922 - accuracy: 0.0227
Epoch 3/200
32/32 [==============================] - 2s 57ms/step - loss: 76.5481 - accuracy: 0.0282
Epoch 4/200
32/32 [==============================] - 2s 54ms/step - loss: 76.4478 - accuracy: 0.0015
Epoch 5/200
32/32 [==============================] - 2s 53ms/step - loss: 76.3543 - accuracy: 0.1524
Epoch 6/200
32/32 [==============================] - 2s 54ms/step - loss: 76.2640 - accuracy: 0.0443
Epoch 7/200
32/32 [==============================] - 2s 54ms/step - loss: 76.1591 - accuracy: 0.1864
Epoch 8/200
32/32 [==============================] - 2s 54ms/step - loss: 76.0932 - accuracy: 0.0421
Epoch 9/200
32/32 [==============================] - 2s 53ms/step - loss: 76.0349 - accuracy: 0.0642
Epoch 10/200
32/32 [==============================] - 2s 54ms/step - loss: 75.9736 - accura

In [36]:
x_en = np.expand_dims(train_dataset['x'],axis=1)
x_en = autoencoder.predict(x_en)
x_en = x_en.reshape(x_en.shape[0], x_en.shape[2])

In [37]:
x_en.shape

(3969, 14)

In [38]:
from loglizer.loglizer.models import LogClustering

model = LogClustering()
model.fit(x_en)

====== Model summary ======
Starting offline clustering...
Processed 1000 instances.
Found 1 clusters offline.

Starting online clustering...
Processed 2000 instances.
Processed 3969 instances.
Found 2 clusters online.



In [44]:
pred_train = model.predict(x_en)
pred_train

array([0., 0., 0., ..., 0., 0., 0.])

In [45]:
count, total = 0, 0
for true, pred in zip(y_train, pred_train):
    if int(true) == int(pred):
        count += 1
    total += 1

count / total

0.9606953892668179

In [49]:
x_ent = np.expand_dims(train_dataset['x'],axis=1)
x_ent = autoencoder.predict(x_ent)
x_ent = x_ent.reshape(x_ent.shape[0], x_ent.shape[2])

pred_test = model.predict(x_ent)
pred_test

array([0., 0., 0., ..., 0., 0., 0.])

In [50]:
count, total = 0, 0
for true, pred in zip(y_test, pred_test):
    if int(true) == int(pred):
        count += 1
    total += 1

count / total

0.9604434366339129